In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Import & Explore Data

In [8]:
#import dataset
df = pd.read_csv("C:/Users/chapa/Desktop/retail-sales-analytics/data/raw/sample_superstore.csv", encoding='latin-1')

In [20]:
#Shape and Columns
print("Shape:\n", df.shape)
print("\nColumns:\n",df.columns.tolist())

#Data Types
print("\nData Types:")
print(df.dtypes)

# Explore Rows
print("\nFirst 5 Rows:")
df.head(5)

Shape:
 (9994, 21)

Columns:
 ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

Data Types:
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

First 5 Rows:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [21]:
# Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [23]:
# Duplicate Rows
print(f"\nDuplicate Rows: {df.duplicated().sum()}")

Duplicate Rows: 0

## 2. Data Cleaning

In [24]:
# Create a copy of raw data
df_clean = df.copy()

In [26]:
# Convert date columns to datetime
df_clean['Order Date'] = pd.to_datetime(df_clean['Order Date'])
df_clean['Ship Date'] = pd.to_datetime(df_clean['Ship Date'])

In [27]:
# Convert Zip Code to String
df_clean['Postal Code'] = df_clean['Postal Code'].astype(str)

In [28]:
# Standardize Text Cols
text_cols = ['Ship Mode','Segment','Country','City','State','Region','Category','Sub-Category']

for col in text_cols:
    df_clean[col] = df_clean[col].str.strip().str.title()
    
    
print(f"Shape: {df_clean.shape}")

Shape: (9994, 21)

In [29]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## 3. Feature Engineering

In [30]:
# Extract date features from order date
df_clean['Order Year'] = df_clean['Order Date'].dt.year
df_clean['Order Month'] = df_clean['Order Date'].dt.month
df_clean['Order Month Name'] = df_clean['Order Date'].dt.strftime('%B')
df_clean['Order Quarter'] = df_clean['Order Date'].dt.quarter

# We can figure out how many days it took to ship an item
df_clean['Days to Ship'] = (df_clean['Ship Date'] - df_clean['Order Date']).dt.days

# We can also find profit margin per order
df_clean['Profit Margin Percentage'] = ((df_clean['Profit'] / df_clean['Sales']) * 100).round(2)

In [31]:
print(f"New Shape: {df_clean.shape}")
print(f"\nNew Columns Added:")
print(['Order Year', 'Order Month','Order Month Name', 'Order Quarter', 'Days to Ship','Profit Margin Percentage'])

New Shape: (9994, 27)

New Columns Added:
['Order Year', 'Order Month', 'Order Month Name', 'Order Quarter', 'Days to Ship', 'Profit Margin Percentage']

## 4. Verify Data

In [32]:
# Verify Data is Correct
print("Order Date Range")
print(f"    Earliest  : {df_clean['Order Date'].min().date()}")
print(f"    Latest   : {df_clean['Order Date'].max().date()}")

Order Date Range
    Earliest  : 2014-01-03
    Latest   : 2017-12-30

In [34]:
# Check for Negative Shipping Days
neg_ship = (df_clean['Days to Ship'] < 0).sum()
print(f"\nNegative Shipping Days: {neg_ship}")

Negative Shipping Days: 0

In [35]:
# Lets look at Days To Ship summary
print(f"\nDays to Ship Summary:")
print(df_clean['Days to Ship'].describe().round(2))

Days to Ship Summary:
count    9994.00
mean        3.96
std         1.75
min         0.00
25%         3.00
50%         4.00
75%         5.00
max         7.00
Name: Days to Ship, dtype: float64

In [37]:
# Check if Zip Code was converted to STR
print(f"\nPostal Code Dtype: {df_clean['Postal Code'].dtype}")

Postal Code Dtype: object

In [38]:
# Preview Clean Data
df_clean.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Order Year,Order Month,Order Month Name,Order Quarter,Days to Ship,Profit Margin Percentage
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,11,November,4,3,16.00
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,11,November,4,3,30.00
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,6,June,2,4,47.00
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,10,October,4,7,-40.00
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,10,October,4,7,11.25

## 5. Export Clean Data

In [39]:
# save as csv
df_clean.to_csv('C:/Users/chapa/Desktop/retail-sales-analytics/data/clean/sales_clean.csv', index=False)

# save to excel
df_clean.to_excel('C:/Users/chapa/Desktop/retail-sales-analytics/data/clean/sales_clean.xlsx', index=False)